// <auto-generated />
using System;
using BookStore.Infrastructure.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Infrastructure.DataAcess.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    partial class BookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Common.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Cara Hunter",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poloisiye-Kurgu",
                            DiscountRate = 0.2m,
                            GenreId = 3,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 210m,
                            Stock = 0,
                            Title = "Felix'in evide ne oldu?",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Author = "N. Crawford",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Psikoloji.....",
                            DiscountRate = 0.15m,
                            GenreId = 2,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 205m,
                            Stock = 0,
                            Title = "Yılanlar Bahçesi",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Cara Hunter",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poloisiye-Kurgu",
                            DiscountRate = 0.2m,
                            GenreId = 3,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 210m,
                            Stock = 0,
                            Title = "Felix'in evide ne oldu 2?",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Platon",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Süper klitap",
                            DiscountRate = 0.15m,
                            GenreId = 1,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 110m,
                            Stock = 0,
                            Title = "Sokrat'ın savunması",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Cara Hunter",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poloisiye-Kurgu",
                            DiscountRate = 0.2m,
                            GenreId = 1,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 210m,
                            Stock = 0,
                            Title = "Felix'in evide ne oldu?",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Cara Hunter",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poloisiye-Kurgu",
                            DiscountRate = 0.2m,
                            GenreId = 3,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 210m,
                            Stock = 0,
                            Title = "Felix'in evide ne oldu?",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Cara Hunter",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Poloisiye-Kurgu",
                            DiscountRate = 0.2m,
                            GenreId = 2,
                            ImageUrl = "https://i.dr.com.tr/cache/154x170-0/originals/0002103875001-1.jpg",
                            Price = 210m,
                            Stock = 0,
                            Title = "Felix'in evide ne oldu?",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookStore.Common.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Felsefe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Psikoloji"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Edebiyat"
                        });
                });

            modelBuilder.Entity("BookStore.Common.Entities.Book", b =>
                {
                    b.HasOne("BookStore.Common.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookStore.Common.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
